version: "3"
services:
    # project
    app:
        container_name: dartweek-academia-do-flutter
        build:
            args:
                user: academia-do-flutter
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./dw-copa-do-mundo/:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

        networks:
            - dartweek-academia-do-flutter
        depends_on:
            - mysql

    # nginx
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./dw-copa-do-mundo:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - dartweek-academia-do-flutter
        depends_on:
            - app

    # db mysql
    mysql:
        container_name: mysql
        image: mariadb:latest
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE:  laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 8889:3306
        networks:
            - dartweek-academia-do-flutter
     # Servidor de E-mail
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - "8003:1025"
            - "8100:8025"
        networks:
            - dartweek-academia-do-flutter

    #PHPMYADMIN  Service
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      restart: always
      ports:
        - 8181:80
      networks:
        - dartweek-academia-do-flutter
      depends_on:
        - mysql
   
networks:
    dartweek-academia-do-flutter:
        driver: bridge